### PR TITLE
CAR-157: Mobile App: Issues with Secure Mail

### PR DESCRIPTION
**Pull request by gitofwebmobiledev**
Keyboard overlapping issue has been fixed

### CODE REVIEW

**Comment by jpnarkinsky** [comment]
Requesting review from @tbowler and @filipvk .  Guys, can you please also take a look?  Thanks!

**Comment by filipvk** [comment]
Looks fine to me, as long as it works properly on Marko's side. This repository is not supposed to include any sensitive application logic since it's just a Cordova wrapper of the `bundle.js` which is generated by `hc-reactui`.

**Comment by gitofwebmobiledev** [comment]
@filipvk That's correct. In addition to, there are some plugins and customization of index.html.

**Comment by jpnarkinsky** [comment]
Why are we copying all the assets?

**Comment by gitofwebmobiledev** [comment]
because we are using them on our app. so straightforward. @jpnarkinsky

**Comment by jpnarkinsky** [comment]
Why are we copying them into the repo rather than copying them as part of the build process?  If we make a change to assets we will have to change them in the mobile repo as well.  This is not normalized!

**Comment by jpnarkinsky** [comment]
Is there any reason we couldn't incorporate the build process for a Cordova app into the hc-reactui repo?  That would make more sense to my way of thinking and would avoid the possibility of the two repos getting out of sync.

**Comment by gitofwebmobiledev** [comment]
In the hc-reactui repo, we can't make mobile platforms for both iOS and android. That's why we need cordova project and import bundle.

**Comment by jpnarkinsky** [comment]
Can you explain the details of why?  I find that very surprising.

**Comment by gitofwebmobiledev** [comment]
@filipvk can you please explain about your thought?

**Comment by jpnarkinsky** [comment]
For long-term maintainability, I do not want to upload the same assets in two separate repos.

Regarding creation of mobile platforms, I assume there's some sort of build script, and we an incorporate that build script into the `package.json` for hc-reactui.  I'm open to a good reason why this is not a good idea, but so far I don't have one.

**Comment by filipvk** [comment]
@gitofwebmobiledev Please be advised that the nature of Cordova project is solely defined by the existence of `config.xml`.

By checking this, Cordova CLI decides whether a certain folder is a Cordova project or not. Of course, we do also have `package.json` for the plugin registration and such, however, you can easily merge them into existing configuration of `hc-reactui`. I also do not have direct experience with merging Cordova environment into existing React projects, but as far as I looking, it shouldn't be too difficult if you can write up some build scripts. Please note that we already have plenty of custom build scripts in `hc-reactui` that Patrick wrote a long time ago (I guess) so you can actually start from there.

**Comment by jpnarkinsky** [comment]
If we can merge this with hc-reactui, is there any reason we need this repo?  @gitofwebmobiledev

**Comment by jpnarkinsky** [comment]
No, Marco created it in his personal Github and we moved it in here just to get it out of his personal github.  I definitely don't want to be storing the same data in two different places!  Regression nightmare.

**Comment by tbowler** [comment]
@jpnarkinsky Should we close this repo?

**Pull request merged**
